# Use a lightweight Python image
FROM python:3.12

# Set the working directory in the Docker image
WORKDIR /mlflow

# Copy the requirements file into the image
COPY requirements.txt /mlflow/

# Install dependencies from the requirements file
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for the application
EXPOSE 5000

# Command to start MLflow server


